runtime: go
api_version: go1
manual_scaling:

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /favicon
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /static
  static_dir: static
- url: /.*
  script: _go_app
